# name: Release
# on:
#   push:
#     branches: [master]
#     paths:
#       - ".changeset/**"             # only run when release intent exists
#       - "packages/erebus-sdk/**"

# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: oven-sh/setup-bun@v2
#         with:
#           bun-version: latest
#           with:
#           registries: https://registry.npmjs.org/